# Generated by Django 5.0.6 on 2024-06-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERC20",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_address",
                    models.CharField(max_length=100, verbose_name="Contract address"),
                ),
                (
                    "contract_name",
                    models.CharField(max_length=100, verbose_name="Contract name"),
                ),
                (
                    "solidity_version",
                    models.CharField(max_length=100, verbose_name="Solidity version"),
                ),
                ("source_code", models.TextField()),
                ("is_erc20", models.BooleanField(blank=True, null=True)),
                (
                    "erc20_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wait_processing", "Wait processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("", "Default"),
                        ],
                        default="",
                        max_length=128,
                        verbose_name="Status of contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "ERC20",
                "verbose_name_plural": "ERC20",
            },
        ),
    ]
