version: '2'
services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./detector:/detector
    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16-alpine3.18
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}


  redis:
    image: redis:7.0-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A detector worker --loglevel=info
    volumes:
      - ./detector:/detector

    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    links:
      - redis
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
    entrypoint: celery
    command: -A detector beat --loglevel=info

    environment:
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

    volumes:
      - ./detector:/detector

    depends_on:
      - worker
      - redis
